<?php

use function PHPSTORM_META\map;

return [
    'flights' => "Flights",
    'airports' => "Airports",
    'city' => "City",
    'select_city' => "Please select a city",
    'submit' => "Submit",
    'id' => "Id",
    'name' => "Name",
    'email' => "Email",
    'password' => "Password",
    'action' => "Action",
    'edit' => "Edit",
    'employee' => "Scanner",
    'supervisor' => "Supervisor",    
    'logout' => "Log out",
    'account' => "Account",
    'flight_number' => "Flight Number",
    'airlines' => "Airlines",
    'select_airlines' => "Select Airlines",
    'take_off_date' => "Take off date",
    'take_off_time' => "Take off time",
    'number_of_passengers' => "Number of passengers",
    'airport' => "Airport",
    'open' => "Open",
    'start_scanning' => "Start scanning",
    'add' => "Add",
    'reload' => "Reload",
    'date' => "Date",
    'passengers' => "Passengers",
    'arrival_city' => "Arrival City",
    'arrival_time' => "Arrival Time",
    'departure_city' => "Departure City",
    'departure_time' => "Departure Time",
    'average_pilgrim_waiting' => "Arrival Pilgrim Waiting",
    'average_pilgrim_service' => "Arrival Pilgrim Service",
    'close' => "Close",

    // Form Departure
    'counters_working_start_time' => 'Counters working start time',
    'counters_working_end_time' => 'Counters working end time',
    'working_counts' => 'Working Counts',
    'non_working_counts' => 'Non-working counts',
    'non_working_counts' => 'Non-working counts',
    'non_working_counts' => 'Non-working counts',
    'number_of_men' => 'Number of men',
    'number_of_women' => 'Number of women',
    'number_of_people_fingerprinted' => 'Number of people fingerprinted',
    'number_of_bags' => 'Number of bags',
    'recommendations' => 'Recommendations',
    'reviews' => 'Reviews',
    'treatment' => 'Treatment',
    'challenges' => 'Challenges',
    'speed_of_communication' => 'Speed of communication',
    'connection_status' => 'Connection Status',
    'fingerprint_status' => 'Fingerprint Status',
    'departure_airport' => 'Destination Airport',
    'number_of_seats' => 'Number of seats',
    'number_of_cases' => 'Number of cases',
    'success' => "Success",
    'warning' => "Warning",
    
    // Arrival Form
    'number_of_counter_custom_staffs' => 'Number of custom counter staffs',
    'number_of_staffs' => 'Number of staffs',
    'flight_delay' => 'Flight Delay',
    'take_off_place' => 'Take off place',
    'expected_arrival_time' => 'Expected arrival time',
    'average_waiting_time_unitil_access' => 'Average waiting time until access to sterile lounges',
    'average_waiting_time_unitil_end_of_inspection' => 'Average service time from sorting until the end of the inspection for luggage',
    'average_waiting_until_sorting_system' => 'Aaverage waiting time in the sorting system until bus rides',
    'how_long_does_luggage_arrive_at' => 'How long does luggage arrive at the residence?',
    'duration_of_arrival_pilgrims' => 'Duration of arrival of pilgrims',
    'number_of_buses_operated_to_transport_pilgrims' => 'Number of buses operated (ready) to transport pilgrims',
    'number_of_buses_operating_with_mecca_logo' => 'Number of buses operating with mecca logo on them',
    'are_there_unmarked_buses' => 'Are there unmarked buses?',
    'are_there_any_accidents' => 'Are there any accidents?',
    'solutions' => 'Solutions',
    'arrival_form_submitted' => 'Arrival form submitted successfully',
    'departure_form_submitted' => 'Departure form submitted successfully',

    'status' => "Status",
    'not_opened' => "Not Opened",
    'opened' => "Opened",
    'check_in' => "Check In",
    'check_out' => "Check Out",
    'closed' => "Closed",
    'on_air' => "On Air",
    'arrived' => "Arrived",
    'complete' => "Complete",
    

    // Login page
    'login' => "Login",
    'login_desc' => "Pease enter your details to login",    
    'login_password_generate' => "If you are trying to login for the first time your password will be the password you give when you are first time login",

    // Form validation
    'field_required' => "This field is required",
    'field_unique' => "This field should be unique",
    'field_not_email' => "This field should be a valid email",
    'forgot_password' => "Forgot password?",
    'forgot_password_desc' => "Input your email to generate new password",

    'create_password' => "Create password",
    'create_password_desc' => "Create your new password",

    'new_password' => "New password",
    'retype_password' => "Retype password",

    'email_password_combination_wrong' => "Email/Password combination is wrong",
    'remember_password' => "Remember your password?",
    'email_not_found' => "Email not found",
    'reset_password_email_subject' => "Reset your password",
    'email_sent_for_reset_password' => "An email with change password link has been sent to (:email)",
    'password_does_not_match' => "Password does not match",
    'password_reset_successful' => "Password reset is successful",
    'change_password' => "Change password",
    'change_language_to_arabic' => "Change language to arabic",
    'change_language_to_english' => "Change language to english",

    'type' => "Type",
    'source' => "Source",
    'destination' => "Destination",
    'select_type' => "Select Type",

    'source_airport' => "Source Airport",
    'destination_airport' => "Destination Airport",
    'select_airport' => "Select an airport",

    'scan_flight' => "Scan flight (:flight)",
    'scan_flight_desc' => "Start scanning for the flight",
    'flight_num' => "Flight <span class='text-primary'>(:num)</span>",
    'source_airport' => "Source Airport",
    'saudi_time' => "Saudi Arrival Time",
    'saudi_date' => "Saudi Arrival Date",
    'special' => "Special Need",
    'special_need' => "Special Need?",

    'view_log' => "View Log",
    'logs_for' => "Logs for (:flight)",
    'no_data' => "No Data",
    'success' => "Success",
    'scan_another' => "Scan Another",

    'assessment_form' => "Assessment form",
    'departure_form_submit' => "Leave Form Submit",
    'arrival_form_submit' => "Arrival Form Submit",

    'departure_flights' => "Departure Flights",
    'close_flight' => "Close Flight",
    'already_checked_in' => "This id is already checked in",
    'already_checked_out' => "This id is already checked out",
    'ok' => "Ok",

    'arrival_flights' => "Arrival Flights",
    'completed_flights' => "Completed flights",

    'excellent' => "Excellent",
    'good' => "Good",
    'weak' => "Weak",

    'no_delay' => "There is no delay",
    'delay' => "There is delay",

    'yes' => "Yes",
    'no' => "No",

    'view_summery' => "View summery"
];

